[[profile]]
name = "laptop"
exec = ["notify-send shikane \"profile $SHIKANE_PROFILE_NAME has been applied\" -u low"]

[[profile.output]]
enable = true
search = "eDP-1"
mode = "3840x2400@60Hz"
scale = 2.0
position = "0,0"
transform = "normal"
adaptive_sync = true
