[[profile]]
name = "laptop"
exec = ["notify-send shikane \"profile $SHIKANE_PROFILE_NAME has been applied\" -u low"]

[[profile.output]]
enable = true
search = "eDP-1"
mode = "3840x2400@60Hz"
scale = 2.0
position = "0,0"
transform = "normal"
adaptive_sync = true


[[profile]]
name = "docked"

[[profile.output]]
enable = true
search = ["m=U28H75x", "s=HTPJ700579", "v=Samsung Electric Company"]
mode = "3840x2160@59.997Hz"
scale = 1.5
position = "0,0"
transform = "normal"
adaptive_sync = true

[[profile.output]]
enable = false
search = "eDP-1"
