export PATH="$PATH:$HOME/script:$CARGO_HOME/bin"

# env
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_DOWNLOAD_DIR="$HOME/dl"
export XDG_DOCUMENTS_DIR="$HOME/docs"
export XDG_PICTURES_DIR="$HOME/media/pics"
export XDG_MUSIC_DIR="$HOME/media/music"
export XDG_VIDEOS="$HOME/media/vids"

export TERMINAL="kitty"
export SHELL="zsh"
export EDITOR="hx"
export VISUAL="hx"
export BROWSER="chromium"
export TASKMGR="btm"
export READER="zathura"
export FILE="nnn"
export KEYBINDER="sxhkd"
export WM="bspwm"

# alias
alias sudo="sudo "
alias ls="exa"
alias la="exa -a"
alias ll="exa -la"
alias rm="rmtrash"
alias rmdir="rmdirtrash"
alias realrm="rm -v"
alias cp="cp -iv"
alias mv="mv -iv"
alias mkdir="mkdir -pv"
alias sk="sk --preview='bat {} --color=always'"
alias vim="nvim"
alias vi="nvim"
alias myip="curl ipinfo.io/ip"
alias untar="tar -zxvf"
alias sha="shasum -a 256"
alias yt="youtube-dl --add-metadata -i"
alias yta="yt -x -f bestaudio/best -i"
alias g="git"
alias ssh="kitty +kitten ssh" # automatically copy terminfo to remote
alias pi="ssh pi@192.168.1.102"
alias zellij="zellij --layout compact"

# clean home
export RUSTUP_HOME="$XDG_DATA_HOME/rustup"
export CARGO_HOME="$XDG_DATA_HOME/cargo"
export CARGO_TARGET_DIR="$XDG_CACHE_HOME/target"
export JAVA_HOME="$XDG_DATA_HOME/java"
export _JAVA_OPTIONS="-Djava.util.prefs.userRoot=$XDG_CONFIG_HOME/java"
export GOPATH="$XDG_DATA_HOME/go"
export CUDA_CACHE_PATH="$XDG_CACHE_HOME/nv"
export WAKATIME_HOME="$XDG_CONFIG_HOME/wakatime"
export PASSWORD_STORE_DIR="$XDG_DATA_HOME/password-store"
export GNUPGHOME="$XDG_DATA_HOME/gnupg"

